digraph experiment {
  imports="['./lib/trace-phases.js', './lib/device-phases.js']";

  input_nw -> fileToBuffer -> gunzipAndDecode -> ejsFabricator -> trace;
  trace -> traceFilter -> traceTree -> tracePrettyPrint -> log;
  input_w -> fileToBuffer;
  input_steps -> fileToBuffer;

  input_w [data="whitespace/example.ejs"];
  input_nw [data="whitespace/exampleNoText.ejs"];
  input_steps [data="whitespace/steps.ejs"];
  traceFilter [traceEvents="['Document::updateStyle']"];
  tracePrettyPrint [showTrace="false"];
  log [tags="['data','ejsFabricator']"];
  trace [browser="system"];
}

