var CSSModel = {};

CSSModel.inheritedPropertyNames = [
    "color", "direction", "font-family", "font-kerning", "font-size", "font-stretch", "font-style", "font-variant", "font-variant-ligatures",
    "font-weight", "-webkit-font-feature-settings", "-webkit-font-smoothing", "-webkit-locale", "-webkit-text-orientation",
    "-webkit-writing-mode", "text-rendering", "border-collapse", "caption-side", "clip-rule", "color-interpolation",
    "color-interpolation-filters", "color-rendering", "cursor", "empty-cells", "fill", "fill-opacity", "fill-rule",
    "glyph-orientation-horizontal", "glyph-orientation-vertical", "image-rendering", "letter-spacing", "line-height",
    "list-style-image", "list-style-position", "list-style-type", "marker-end", "marker-mid", "marker-start", "orphans",
    "overflow-wrap", "paint-order", "pointer-events", "quotes", "shape-rendering", "speak", "stroke", "stroke-dasharray",
    "stroke-dashoffset", "stroke-linecap", "stroke-linejoin", "stroke-miterlimit", "stroke-opacity", "stroke-width", "tab-size", "text-align",
    "text-align-last", "text-anchor", "text-indent", "text-justify", "text-shadow", "text-transform", "text-underline-position",
    "touch-action-delay", "visibility", "-webkit-border-horizontal-spacing", "-webkit-border-vertical-spacing", "-webkit-box-direction",
    "-webkit-highlight", "-webkit-hyphenate-character", "-webkit-line-box-contain", "-webkit-line-break", "-webkit-print-color-adjust",
    "-webkit-rtl-ordering", "-webkit-ruby-position", "-webkit-tap-highlight-color", "-webkit-text-combine", "-webkit-text-emphasis-color",
    "-webkit-text-emphasis-position", "-webkit-text-emphasis-style", "-webkit-text-fill-color", "-webkit-text-security",
    "-webkit-text-stroke-color", "-webkit-text-stroke-width", "-webkit-user-modify", "-webkit-user-select", "white-space", "widows",
    "word-break", "word-spacing", "word-wrap", "writing-mode", "-webkit-text-decorations-in-effect"];

CSSModel.propertyDefaults = {
    "background-attachment": "scroll",
    "background-blend-mode": "normal",
    "background-clip": "border-box",
    "background-color": "rgba(0, 0, 0, 0)",
    "background-image": "none",
    "background-origin": "padding-box",
    "background-position": "0% 0%",
    "background-repeat": "repeat",
    "background-size": "auto",
    "border-bottom-color": "rgb(0, 0, 0)",
    "border-bottom-left-radius": "0px",
    "border-bottom-right-radius": "0px",
    "border-bottom-style": "none",
    "border-bottom-width": "0px",
    "border-collapse": "separate",
    "border-image-outset": "0px",
    "border-image-repeat": "stretch",
    "border-image-slice": "100%",
    "border-image-source": "none",
    "border-image-width": "1",
    "border-left-color": "rgb(0, 0, 0)",
    "border-left-style": "none",
    "border-left-width": "0px",
    "border-right-color": "rgb(0, 0, 0)",
    "border-right-style": "none",
    "border-right-width": "0px",
    "border-top-color": "rgb(0, 0, 0)",
    "border-top-left-radius": "0px",
    "border-top-right-radius": "0px",
    "border-top-style": "none",
    "border-top-width": "0px",
    "bottom": "auto",
    "box-shadow": "none",
    "box-sizing": "content-box",
    "caption-side": "top",
    "clear": "none",
    "clip": "auto",
    "color": "rgb(0, 0, 0)",
    "cursor": "auto",
    "direction": "ltr",
    "display": "block",
    "empty-cells": "show",
    "float": "none",
    "font-family": "'Times New Roman'",
    "font-kerning": "auto",
    "font-size": "16px",
    "font-stretch": "normal",
    "font-style": "normal",
    "font-variant": "normal",
    "font-variant-ligatures": "normal",
    "font-weight": "normal",
    "height": "1432px",
    "image-rendering": "auto",
    "isolation": "auto",
    "left": "auto",
    "letter-spacing": "normal",
    "line-height": "normal",
    "list-style-image": "none",
    "list-style-position": "outside",
    "list-style-type": "disc",
    "margin-bottom": "0px",
    "margin-left": "0px",
    "margin-right": "0px",
    "margin-top": "0px",
    "max-height": "none",
    "max-width": "none",
    "min-height": "0px",
    "min-width": "0px",
    "mix-blend-mode": "normal",
    "object-fit": "fill",
    "object-position": "50% 50%",
    "opacity": "1",
    "orphans": "auto",
    "outline-color": "rgb(0, 0, 0)",
    "outline-offset": "0px",
    "outline-style": "none",
    "outline-width": "0px",
    "overflow-wrap": "normal",
    "overflow-x": "visible",
    "overflow-y": "visible",
    "padding-bottom": "0px",
    "padding-left": "0px",
    "padding-right": "0px",
    "padding-top": "0px",
    "page-break-after": "auto",
    "page-break-before": "auto",
    "page-break-inside": "auto",
    "pointer-events": "auto",
    "position": "static",
    "resize": "none",
    "right": "auto",
    "speak": "normal",
    "table-layout": "auto",
    "tab-size": "8",
    "text-align": "start",
    "text-decoration": "none",
    "text-indent": "0px",
    "text-rendering": "auto",
    "text-shadow": "none",
    "text-overflow": "clip",
    "text-transform": "none",
    "top": "auto",
    "touch-action": "auto",
    "transition-delay": "0s",
    "transition-duration": "0s",
    "transition-property": "all",
    "transition-timing-function": "ease",
    "unicode-bidi": "normal",
    "vertical-align": "baseline",
    "visibility": "visible",
    "white-space": "normal",
    "widows": "1",
    "width": "1280px",
    "will-change": "auto",
    "word-break": "normal",
    "word-spacing": "0px",
    "word-wrap": "normal",
    "z-index": "0",
    "zoom": "1",
    "-webkit-animation-delay": "0s",
    "-webkit-animation-direction": "normal",
    "-webkit-animation-duration": "0s",
    "-webkit-animation-fill-mode": "none",
    "-webkit-animation-iteration-count": "1",
    "-webkit-animation-name": "none",
    "-webkit-animation-play-state": "running",
    "-webkit-animation-timing-function": "ease",
    "-webkit-appearance": "none",
    "backface-visibility": "visible",
    "-webkit-backface-visibility": "visible",
    "-webkit-background-clip": "border-box",
    "-webkit-background-composite": "source-over",
    "-webkit-background-origin": "padding-box",
    "-webkit-background-size": "auto",
    "-webkit-border-horizontal-spacing": "0px",
    "-webkit-border-image": "none",
    "-webkit-border-vertical-spacing": "0px",
    "-webkit-box-align": "stretch",
    "-webkit-box-decoration-break": "slice",
    "-webkit-box-direction": "normal",
    "-webkit-box-flex": "0",
    "-webkit-box-flex-group": "1",
    "-webkit-box-lines": "single",
    "-webkit-box-ordinal-group": "1",
    "-webkit-box-orient": "horizontal",
    "-webkit-box-pack": "start",
    "-webkit-box-reflect": "none",
    "-webkit-box-shadow": "none",
    "-webkit-clip-path": "none",
    "-webkit-column-break-after": "auto",
    "-webkit-column-break-before": "auto",
    "-webkit-column-break-inside": "auto",
    "-webkit-column-count": "auto",
    "-webkit-column-gap": "normal",
    "-webkit-column-rule-color": "rgb(0, 0, 0)",
    "-webkit-column-rule-style": "none",
    "-webkit-column-rule-width": "0px",
    "-webkit-column-span": "none",
    "-webkit-column-width": "auto",
    "-webkit-filter": "none",
    "align-content": "start",
    "align-items": "start",
    "align-self": "start",
    "flex-basis": "auto",
    "flex-grow": "0",
    "flex-shrink": "1",
    "flex-direction": "row",
    "flex-wrap": "nowrap",
    "justify-content": "start",
    "-webkit-font-smoothing": "auto",
    "-webkit-highlight": "none",
    "-webkit-hyphenate-character": "auto",
    "-webkit-line-box-contain": "block inline replaced",
    "-webkit-line-break": "auto",
    "-webkit-line-clamp": "none",
    "-webkit-locale": "auto",
    "-webkit-margin-before-collapse": "collapse",
    "-webkit-margin-after-collapse": "collapse",
    "-webkit-mask-box-image": "none",
    "-webkit-mask-box-image-outset": "0px",
    "-webkit-mask-box-image-repeat": "stretch",
    "-webkit-mask-box-image-slice": "0 fill",
    "-webkit-mask-box-image-source": "none",
    "-webkit-mask-box-image-width": "auto",
    "-webkit-mask-clip": "border-box",
    "-webkit-mask-composite": "source-over",
    "-webkit-mask-image": "none",
    "-webkit-mask-origin": "border-box",
    "-webkit-mask-position": "0% 0%",
    "-webkit-mask-repeat": "repeat",
    "-webkit-mask-size": "auto",
    "order": "0",
    "perspective": "none",
    "-webkit-perspective": "none",
    "perspective-origin": "640px 716px",
    "-webkit-perspective-origin": "640px 716px",
    "-webkit-print-color-adjust": "economy",
    "-webkit-rtl-ordering": "logical",
    "shape-outside": "none",
    "shape-image-threshold": "0",
    "shape-margin": "0px",
    "-webkit-tap-highlight-color": "rgba(0, 0, 0, 0.180392)",
    "-webkit-text-combine": "none",
    "-webkit-text-decorations-in-effect": "none",
    "-webkit-text-emphasis-color": "rgb(0, 0, 0)",
    "-webkit-text-emphasis-position": "over",
    "-webkit-text-emphasis-style": "none",
    "-webkit-text-fill-color": "rgb(0, 0, 0)",
    "-webkit-text-orientation": "vertical-right",
    "-webkit-text-security": "none",
    "-webkit-text-stroke-color": "rgb(0, 0, 0)",
    "-webkit-text-stroke-width": "0px",
    "transform": "none",
    "-webkit-transform": "none",
    "transform-origin": "640px 716px",
    "-webkit-transform-origin": "640px 716px",
    "transform-style": "flat",
    "-webkit-transform-style": "flat",
    "-webkit-transition-delay": "0s",
    "-webkit-transition-duration": "0s",
    "-webkit-transition-property": "all",
    "-webkit-transition-timing-function": "ease",
    "-webkit-user-drag": "auto",
    "-webkit-user-modify": "read-only",
    "-webkit-user-select": "text",
    "-webkit-writing-mode": "horizontal-tb",
    "-webkit-app-region": "no-drag",
    "buffered-rendering": "auto",
    "clip-path": "none",
    "clip-rule": "nonzero",
    "mask": "none",
    "filter": "none",
    "flood-color": "rgb(0, 0, 0)",
    "flood-opacity": "1",
    "lighting-color": "rgb(255, 255, 255)",
    "stop-color": "rgb(0, 0, 0)",
    "stop-opacity": "1",
    "color-interpolation": "srgb",
    "color-interpolation-filters": "linearrgb",
    "color-rendering": "auto",
    "fill": "rgb(0, 0, 0)",
    "fill-opacity": "1",
    "fill-rule": "nonzero",
    "marker-end": "none",
    "marker-mid": "none",
    "marker-start": "none",
    "mask-type": "luminance",
    "shape-rendering": "auto",
    "stroke": "none",
    "stroke-dasharray": "none",
    "stroke-dashoffset": "0",
    "stroke-linecap": "butt",
    "stroke-linejoin": "miter",
    "stroke-miterlimit": "4",
    "stroke-opacity": "1",
    "stroke-width": "1",
    "alignment-baseline": "auto",
    "baseline-shift": "baseline",
    "dominant-baseline": "auto",
    "text-anchor": "start",
    "writing-mode": "lr-tb",
    "glyph-orientation-horizontal": "0deg",
    "glyph-orientation-vertical": "auto",
    "vector-effect": "none",
    "paint-order": "fill stroke markers"
};

module.exports = CSSModel;
