trace -traceFilter-> -traceTree-> -tracePrettyPrint-> output
trace-nostyle -traceFilter-> -traceTree-> -tracePrettyPrint-> output-nostyle
trace-reduced -traceFilter-> -traceTree-> -tracePrettyPrint-> output-reduced
trace-minimized -traceFilter-> -traceTree-> -tracePrettyPrint-> output-minimized

trace: tests/pipeline/simple.trace
trace-nostyle: tests/pipeline/simple-nostyle.trace
trace-reduced: tests/pipeline/simple-reduced.trace
trace-minimized: tests/pipeline/simple-minimized.trace
output: tests/pipeline/simple.dump
output-nostyle: tests/pipeline/simple-nostyle.dump
output-reduced: tests/pipeline/simple-reduced.dump
output-minimized: tests/pipeline/simple-minimized.dump
