digraph experiment {
  imports="['trace-phases', 'test-phases']"

  input_normal [label="input", data="simple.trace"];
  input_nostyle [label="input", data="simple-nostyle.trace"];
  input_reduced [label="input", data="simple-reduced.trace"];
  input_minimized [label="input", data="simple-minimized.trace"];
  traceFilter [traceCategories="['blink.console']"];

  {input_normal; input_nostyle; input_reduced; input_minimized} -> fork -> fileToJSON -> traceFilter -> traceTree -> tracePrettyPrint -> t1To1;

  t1To1 [capture="true"];
}
